### ISSUE TITLE
Unclear usage instructions

### ISSUE THREAD

**Issue by thoni56** [bboc/mdtools#1]
I'm translating the S3 Practical Guide and want to re-build the pdf. I have a fork but as it says in the documentation that relies on `mdtools`, because `make setup` complains about `mdslides` not being available. Coming here I have a hard time to figure out how to put this together.

How do I actually get the `mdslides` command that is referred in the documentation? There is no `mdslides` file, nor any `mdslides.py` in this repo? Are there files missing or some symbolic links that needs to be created?

I'm confused...

**Comment by bboc** [comment]
@thoni56 mdtools v2.0.0 comes with a working setup script and better documentation. It also comes with a lot of new features for the website, see <http://patterns.sociocracy30.org/>. However,  I still need to update the files in crowdin before you can use that, I hope I can get to that in the next couple of days.
